### ISSUE TITLE
Error after Pip Installation

### ISSUE THREAD

**Issue by DSoudis** [easeml/datascope#4]
I am trying to install datascope via pip in a Conda env running on Windows.
After pip i getting an installation without errors but upon importing datascope i get

`from datascope.importance.common import SklearnModelAccuracy`
`from datascope.importance.shapley import ShapleyImportance`

`Traceback (most recent call last):`

`  Input In [2] in <cell line: 2>`
`    from datascope.importance.shapley import ShapleyImportance`

`  File C:\Anaconda3\envs\datashapley\lib\site-packages\datascope\importance\shapley.py:22 in <module>`
`    from .shapley_cy import compute_all_importances_cy`

`ModuleNotFoundError: No module named 'datascope.importance.shapley_cy'`

Any advice?

**Comment by DSoudis** [comment]
Thanks babak-1990,

I can only install using pip my system. I will have to wait and see if something changes.

**Comment by babak-1990** [comment]
what I meant was, If you look at the repository you can see there is setup.py file, you should be able to run it on your local computer after cloning the repository on your local environment. so basically you can do these steps:
1-create an environment using your choice of environment managing tool.(conda, pipenv, python)
2-clone the repository `git clone https://github.com/easeml/datascope.git`
3- install necessary requirements `pip install -r .\requirements.txt  `
4- run the command `python setup.py install `

**Comment by DSoudis** [comment]
Thanks again,

I appreciate this.

I am not working in a local environment. I can only specify the name of a library and then a managed system in the backend uses pip on a proprietary cloud corporate-approved environment. I cannot clone anything anywhere!

**Comment by DSoudis** [comment]
Works fine for me now! Thank you for the fix :)

**Comment by xzyaoi** [comment]
> Works fine for me now! Thank you for the fix :)

Cool! A stable release will be published soon :)
